import { NewsCatcherHeadlinesResponse } from "api/hooks/useGetLatestHeadlines/types.ts"

export const useGetLatestHeadlinesResponses: NewsCatcherHeadlinesResponse = {
  status: "ok",
  total_hits: 10000,
  page: 1,
  total_pages: 200,
  page_size: 50,
  articles: [
    {
      title: "大人用紙おむつメーカー'近澤製紙所'が自己破産申請…負債は約33億円、コロナ禍で受注が大幅減少（高知）",
      author: "テレビ高知",
      published_date: "2023-09-25 16:47:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/741634?display=1",
      clean_url: "tbs.co.jp",
      excerpt: "大人用の紙おむつメーカーで高知県いの町に本社を置く近澤製紙所が、自己破産を申請していたことが分かりました。負債は約33億円だということです。帝国データバンク高知支店によりますと、近澤製紙所は9月15日に… (1ページ)",
      summary: "大人用の紙おむつメーカーで高知県いの町に本社を置く近澤製紙所が、自己破産を申請していたことが分かりました。負債は約33億円だということです。\n帝国データバンク高知支店によりますと、近澤製紙所は9月15日に、高知地裁に自己破産を申請したということです。\n近澤製紙所は1953年に法人化した紙おむつメーカーで、大人用紙おむつを主力商品に、国内製紙メーカーからの委託生産（OEM）を手がけてきました。2018年には売上高約41億5000万円を計上していましたが、新型コロナの影響で海外向けの受注が減少したほか、大手製紙メーカーの内製化に伴い、OEMの受注が大幅に減少していたということです。\nまた、パルプなど原材料価格の高騰分を販売価格に思うように転嫁できず、経営が悪化。人員削減などで改善を図ったものの資金繰りがひっ迫。先行きの見通しが立たなくなったということです。負債は約33億円だということです。",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "TBS NEWS DIG,テレビ高知",
      media: "https://newsdig.ismcdn.jp/mwimgs/5/a/-/img_5adb3549df898a77e04849018be8ca281417713.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "731a5463440865636f1fbc0b59ddd8a8"
    },
    {
      title: "ことしの家康はパティシエです…「名古屋まつり」三英傑・三姫決まる 10月21日・22日に開催",
      author: "CBCテレビ",
      published_date: "2023-09-25 16:47:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/741581?display=1",
      clean_url: "tbs.co.jp",
      excerpt: "その素顔も三者三様。10月に行われる「名古屋まつり」の英傑行列で、主役を務める三英傑（さんえいけつ）が発表されました。ことしで69回目を迎える名古屋まつりは、信長・秀吉・家康の三英傑に扮した市民が市の中… (1ページ)",
      summary: "その素顔も三者三様。10月に行われる「名古屋まつり」の英傑行列で、主役を務める三英傑（さんえいけつ）が発表されました。\n\r\nことしで69回目を迎える名古屋まつりは、信長・秀吉・家康の三英傑に扮した市民が市の中心部を練り歩く行列が最大の見所です。\n\n去年の様子\n\n\n去年の様子\n\n\r\n注目の三英傑は一般公募で選ばれますが、ことしは過去最多となる103人が応募。厳選された3人は実に個性豊かです。信長役の根木浩路さんは開業医。秀吉役の佐藤洋平さんは会社経営者。そして、家康役の長谷川亨平さんは…。\n\n\n\r\n（家康役 長谷川亨平さん）\r\n「パティシエでございます。お菓子の世界の仕事ですので、参加するなんて夢にも思いませんでしたが、還暦を過ぎたらこういうものに挑戦したいと思った」\n\n\n\r\nまた、三姫（さんひめ）役の3人はいずれも百貨店に勤務。参加者の背景は様々ですが、「名古屋を元気にしたい」との思いはひとつでした。「名古屋まつり」は10月21日と22日です。",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "CBCテレビ,TBS NEWS DIG",
      media: "https://newsdig.ismcdn.jp/mwimgs/d/d/-/img_dd6343161d5bc4db625fb29128605ebf155142.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "8b159d1bca0128f7cdb3d77874d33bc6"
    },
    {
      title: "ヤベホームが対馬市のCO2排出権を購入 建材に対馬産ヒノキを使用　市は売上を環境整備や希少生物保護に活用",
      author: "長崎放送",
      published_date: "2023-09-25 16:47:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/741462?display=1",
      clean_url: "tbs.co.jp",
      excerpt: "諫早市の住宅メーカー・ヤベホームが、対馬市が販売している'二酸化炭素吸収量'を5年間継続購入する申請をしました。諫早市のヤベホームは、対馬産のヒノキを建材に使用するなどしていて、これまで10年間にわた… (1ページ)",
      summary: "諫早市の住宅メーカー・ヤベホームが、対馬市が販売している'二酸化炭素吸収量'を5年間継続購入する申請をしました。\n\n諫早市のヤベホームは、対馬産のヒノキを建材に使用するなどしていて、これまで10年間にわたって、対馬市の'二酸化炭素吸収量'を購入してきました。\n\n今回は、今後5年間のCO2排出権、合わせて65トンを65万円で購入し、対馬市役所を訪れた矢部 福徳社長が比田勝市長に購入を報告しました。\n\nヤベホーム　矢部 福徳 社長：\r\n「対馬市の森づくり、そして水産の海づくり、そういうものの基金に投資していただいて、更なる自然豊かな対馬を目指していただければと思っています」\n対馬市では、クレジットの売り上げを環境整備や、希少生物の保護などに活用することにしています。",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "TBS NEWS DIG,長崎放送",
      media: "https://newsdig.ismcdn.jp/mwimgs/2/4/-/img_243fe44d57ca3923a8fca94fa3d6dff1207236.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "dd128c4198fdb00ead72436530f66291"
    },
    {
      title: "大阪万博デザインのナンバープレートが三重県の公用車に　万博本番でブース出展予定",
      author: "CBCテレビ",
      published_date: "2023-09-25 16:46:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/741566?display=1",
      clean_url: "tbs.co.jp",
      excerpt: "2025年に開催される大阪・関西万博にブースを出展する予定の三重県は、万博への機運を高めることを目的に特別デザインのナンバープレートをつけた公用車を新たに導入します。大阪・関西万博デザインのナンバープレ… (1ページ)",
      summary: "2025年に開催される大阪・関西万博にブースを出展する予定の三重県は、万博への機運を高めることを目的に特別デザインのナンバープレートをつけた公用車を新たに導入します。\n\n大阪・関西万博デザインのナンバープレートは、申し込みをした全国の希望者がとりつけることが可能で、10月24日から万博が開催される2025年の12月26日まで交付されます。\n\r\n三重県は県の魅力を世界へ発信することを目的にブースを出展する予定で、その機運を高めることを目的に、このナンバープレートを取り付けた公用車を10月2日から新たに3台導入するということです。また今後、さらに6台の導入を予定しています。",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "CBCテレビ,TBS NEWS DIG",
      media: "https://newsdig.ismcdn.jp/mwimgs/6/d/-/img_6d2e0bc82a2db121f70adb9d9b7b266b1635135.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "e50ee4b463b5c8ca802e5456514d4ac5"
    },
    {
      title: "Ado新曲がアニメ「SPY×FAMILY」新OPに　菅野よう子×SEATBELTS参加に「ビバップの再来か」など反響",
      author: "三輪薫",
      published_date: "2023-09-25 16:45:00",
      published_date_precision: "timezone unknown",
      link: "https://nlab.itmedia.co.jp/nl/articles/2309/25/news139.html",
      clean_url: "itmedia.co.jp",
      excerpt: "全方位に強すぎる。 (1/2)",
      summary: "全方位に強すぎる。",
      rights: "itmedia.co.jp",
      rank: 3371,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "三輪薫",
      media: "https://image.itmedia.co.jp/nl/articles/2309/25/cover_news139.jpg",
      is_opinion: false,
      twitter_account: "@itm_nlab",
      _score: null,
      _id: "9f69232cb5e8bdd5a2e43937b663a2d9"
    },
    {
      title: "路上で刃物のようなものを持った不審者　中学生を追いかけていると通報　警察がパトロール",
      author: "テレビ山梨",
      published_date: "2023-09-25 16:45:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/741496",
      clean_url: "tbs.co.jp",
      excerpt: "25日午前、甲府市徳行の路上で刃物のようなものを持った男に中学生が追いかけられたとという通報があり、警察が周辺をパトロールしています。25日午前10時前、甲府市徳行2丁目の路上で、不審な男が刃物のようなも… (1ページ)",
      summary: "25日午前、甲府市徳行の路上で刃物のようなものを持った男に中学生が追いかけられたとという通報があり、警察が周辺をパトロールしています。\n\n25日午前10時前、甲府市徳行2丁目の路上で、不審な男が刃物のようなものを取り出し、中学生を追いかけていると警察に通報がありました。\n\n甲府市の教育委員会によりますと男は身長160㎝から170㎝で、白っぽい帽子に黒の半袖シャツ、白系ズボン姿だったということです。\nこれまでにけがをした人の情報はありません。\r\n警察は緊急でパトロールを行い、不審者について調べています。\n\nまた、現場周辺の小学校は全校一斉で集団下校の措置をとり、甲府市は防災無線やメールで注意を呼びかけています。",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "TBS NEWS DIG,テレビ山梨",
      media: "https://newsdig.ismcdn.jp/mwimgs/b/0/-/img_b0932f3722878c7c999b7c9a508ede37247593.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "64121bcb9c4027acb9fa341e58615bee"
    },
    {
      title: "Ado新曲がアニメ「SPY×FAMILY」新OPに　菅野よう子×SEATBELTS参加に「ビバップの再来か」など反響（1/2 ページ）",
      author: "三輪薫",
      published_date: "2023-09-25 16:45:00",
      published_date_precision: "timezone unknown",
      link: "https://nlab.itmedia.co.jp/nl/articles/2309/25/news139.html",
      clean_url: "itmedia.co.jp",
      excerpt: "全方位に強すぎる。",
      summary: "Adoさんの新曲「クラクラ」が、テレビアニメ「SPY×FAMILY」Season 2（テレビ東京系列ほか）のオープニング主題歌に決定。「2期OPはAdo」「作詞作曲はmeiyo」「編曲は菅野よう子」「演奏はSEATBELTS」という圧倒的布陣にネットでは「なにそれロイヤルストレートフラッシュすぎるじゃん」「まさかカウボーイビバップの再来か」など大きな期待と反響が起こっています。\n\n\n\n\n\n\n\n\n【主題歌解禁】テレビアニメ「SPY×FAMILY」Season 2本予告\n\n\n\n\n　「SPY×FAMILY」は遠藤達哉さんが集英社のマンガアプリ「少年ジャンプ＋」で2019年3月から連載中の同名漫画を原作としたアニメ。2023年はミュージカルを始め、10月放送開始のアニメ2期、そして初の映画化とイベントめじろ押しとなっています。アニメ「SPY×FAMILY」Season 2の初回放送は10月7日23時からです。\n\n\n\n\n\n\n　アニメ2期のOPに起用された「クラクラ」は、作詞作曲をmeiyoさんが担当し、編曲と演奏を音楽家の菅野よう子さんとSEATBELTSが担当。Adoさんのボーカルが縦横無尽に宙を駆けるジェットコースターのような楽曲に仕上がっているとのことです。\n\n\n\n\n「SPY×FAMILY Season 2」はABEMAでも無料配信 (C)遠藤達哉／集英社・SPY×FAMILY製作委員会\n\n\n　編曲で参加する菅野さんといえば、たぐいまれなる音楽センスをいかんなく発揮し、映画でもゲームでもテレビドラマでもアニメでもCMでも印象的な音楽を生み出してきた生きる伝説。SEATBELTSは菅野さんが率いるバンドで、アニメ「カウボーイビバップ」のOP「Tank!」に代表される楽曲は今でも名曲として語り継がれており、今回の発表にネットでは「若い層と上の年代の両方にアプローチしてくるの抜かりなくて凄い」「令和のこの時代にこの組み合わせがまた見れるとは」「ビバップ難民にとっての宿木が見つかっちまったよ！」など神曲への期待が高まっています。\n\n\n　また、ED主題歌はVaundyさんの新曲「トドメの一撃 feat.",
      rights: "itmedia.co.jp",
      rank: 3371,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "三輪薫",
      media: "https://image.itmedia.co.jp/nl/articles/2309/25/cover_news139.jpg",
      is_opinion: false,
      twitter_account: "@itm_nlab",
      _score: null,
      _id: "e2c318b3986c1015a130c4ce1a52b617"
    },
    {
      title: "「子どもに関わる全ての職業が対象に入っていないと意味がない」'日本版DBS'臨時国会での法案提出を断念する方針　自民党内の議論の背景は？",
      author: "TBSテレビ",
      published_date: "2023-09-25 16:44:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/741579",
      clean_url: "tbs.co.jp",
      excerpt: "性犯罪から子どもを守る「日本版DBS」について、政府は来月予定される臨時国会への法案提出を目指していましたが、断念する方針を固めました。背景には何があったのでしょうか。加藤鮎子こども政策担当大臣「（日… (1ページ)",
      summary: "性犯罪から子どもを守る「日本版DBS」について、政府は来月予定される臨時国会への法案提出を目指していましたが、断念する方針を固めました。背景には何があったのでしょうか。\n\n加藤鮎子こども政策担当大臣\n「（日本版DBSについて）こども家庭庁の方で制度設計を検討してまいります」\n\n政府が検討進める「日本版DBS」。「日本版DBS」は、子どもに関わる仕事に就く人に性犯罪歴がないことを確認する制度で、政府は当初、▼確認の対象を裁判所に認定された前科とする、▼対象となる前科の期間には上限を設けるべきなどとした有識者会議の報告書も踏まえ、来月に予定される臨時国会への提出を目指していました。\n\n政府関係者\n「ジャニーズの性加害問題で世間の要請もあり、スピード重視で早期成立を目指した方が良いと思い進めていた」\n\n岸田総理がこども家庭庁の目玉として掲げていた「日本版DBS」ですが、一転、政府は次の国会での法案提出を断念する方針を固めました。背景には自民党内での議論の行き詰まりがあったといいます。\n\n自民党中堅議員\n「塾講師など、子どもに関わる全ての職業が対象に入っていないと法律を作る意味がないなどの意見",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "TBS NEWS DIG,TBSテレビ",
      media: "https://newsdig.ismcdn.jp/mwimgs/2/f/-/img_2f2cb7b8a43719093d8964033368b3ae385586.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "d3dd2d003bad3332ccca1246a8260c4d"
    },
    {
      title: "アメリカで来年度予算案を巡る協議難航「政府閉鎖」の可能性 (2023年9月25日掲載)",
      author: "AFPBB News",
      published_date: "2023-09-25 16:44:00",
      published_date_precision: "timezone unknown",
      link: "https://news.livedoor.com/topics/detail/25051142",
      clean_url: "livedoor.com",
      excerpt: "米国の会計年度末が迫るなか、来年度予算案を巡る協議が難航している。民主党と共和党との間で合意できない場合、「政府閉鎖」の可能性も。連邦機関の業務が停止し、再選を目指すバイデン氏にもリスクとなりかねない",
      summary: "",
      rights: "livedoor.com",
      rank: 3444,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "AFPBB News",
      media: "https://image.news.livedoor.com/newsimage/stf/9/0/90777_1351_2426eea6_f947ada1.jpg",
      is_opinion: false,
      twitter_account: "@livedoornews",
      _score: null,
      _id: "360ec993edb985a138a9218c7467001a"
    },
    {
      title: "18歳の知人男性を12時間にわたり暴行…「指を詰めろ」と脅迫 (2023年9月25日掲載)",
      author: "MBCニュース",
      published_date: "2023-09-25 16:43:44",
      published_date_precision: "timezone unknown",
      link: "https://news.livedoor.com/topics/detail/25051287",
      clean_url: "livedoor.com",
      excerpt: "18歳の知人男性への暴行・脅迫の罪で、広島市の24歳男が起訴された。12時間にわたり暴行し「裏切ったらお前の家族を殺す」などと脅したそう。自宅で包丁とまな板を置いた状態で「指を詰めろ」と脅迫したという",
      summary: "",
      rights: "livedoor.com",
      rank: 3444,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "MBCニュース",
      media: "https://image.news.livedoor.com/newsimage/stf/d/9/d9247_1782_c71753cfab2a0abbf66acca32da09c43.jpg",
      is_opinion: false,
      twitter_account: "@livedoornews",
      _score: null,
      _id: "590fbcfc67039fae1728e73791860db1"
    },
    {
      title: "F15戦闘機が緊急着陸　飛行訓練中に油圧系統トラブルで千歳基地へ　消防部隊が出動するも火災現象なし　パイロット無事",
      author: "北海道放送",
      published_date: "2023-09-25 16:43:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/741574",
      clean_url: "tbs.co.jp",
      excerpt: "25日正午すぎ、飛行訓練中の航空自衛隊のＦ15戦闘機が、油圧系統のトラブルのため千歳基地に緊急着陸しました。 航空自衛隊によりますと、25日午後０時50分ごろ、飛行訓練中のＦ15戦闘機が、油圧系統のトラブルの… (1ページ)",
      summary: "25日正午すぎ、飛行訓練中の航空自衛隊のＦ15戦闘機が、油圧系統のトラブルのため千歳基地に緊急着陸しました。\n\n　航空自衛隊によりますと、25日午後０時50分ごろ、飛行訓練中のＦ15戦闘機が、油圧系統のトラブルのため千歳基地に緊急着陸しました。\n　滑走路に着陸後、自衛隊の消防部隊が駆け付けましたが、機体に火災現象はなく、放水活動などはしませんでした。\n　またパイロットにも、けがはありませんでした。\n　航空自衛隊が、トラブルの詳しい原因を調べています。",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "TBS NEWS DIG,北海道放送",
      media: "https://newsdig.ismcdn.jp/mwimgs/6/b/-/img_6bd26d9b26a7393913ef2734c560441a154626.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "ef6b726f62acba364896061ad5e4e87f"
    },
    {
      title: "北海道医療大のFビレッジ移転検討に当別町長「大学がないことは考えられない」大学側は27日理事会で移転可否決定か",
      author: "北海道放送",
      published_date: "2023-09-25 16:43:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/741576",
      clean_url: "tbs.co.jp",
      excerpt: "北海道当別町にある北海道医療大学が、北広島市の「Ｆビレッジ」にキャンパスの移転を検討していることについて、当別町長は引き止める方針です。 大学関係者によりますと、北海道医療大学は2028年をめどに北広島… (1ページ)",
      summary: "北海道当別町にある北海道医療大学が、北広島市の「Ｆビレッジ」にキャンパスの移転を検討していることについて、当別町長は引き止める方針です。\n\n　大学関係者によりますと、北海道医療大学は2028年をめどに北広島市の「Ｆビレッジ」の「エスコンフィールドＨＯＫＫＡＩＤＯ」に隣接した場所にキャンパスを移転することを検討しています。\n　これを受けて、当別町の後藤正洋町長は25日、取材に応じ、「町に残ってもらうよう早急に要望する」と話しました。\n\n当別町　後藤正洋町長\n「大学がないことは考えられませんので、この50年間、町と大学とのいろいろな信頼関係を積み重ねてきましたので、そこを大学には踏みとどまっていただきたい」\n\n　大学側は27日開催予定の理事会で移転の可否を決める方針で、当別町は大学に説明を求め、移転しないよう要望することにしています。",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "TBS NEWS DIG,北海道放送",
      media: "https://newsdig.ismcdn.jp/mwimgs/0/1/-/img_01908eb630a72952ab80782ec1889ca8173844.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "eca9dd3132a083cc87de9cd7b673a632"
    },
    {
      title: "冷凍ホタテ10万食を全国の学校給食に無償提供へ　中国の輸入禁止を受けて「事業者に先行きの見える施策を」北海道森町",
      author: "北海道放送",
      published_date: "2023-09-25 16:43:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/741577",
      clean_url: "tbs.co.jp",
      excerpt: "中国が日本の水産物の輸入を禁止していることを受け、北海道南部の森町は、保管されているホタテ10万食を、学校給食として無償で提供する方針を固めました。 水産加工場が集積する森町には、道内各地からホタテが… (1ページ)",
      summary: "中国が日本の水産物の輸入を禁止していることを受け、北海道南部の森町は、保管されているホタテ10万食を、学校給食として無償で提供する方針を固めました。\n\n　水産加工場が集積する森町には、道内各地からホタテが集まりますが、町内の倉庫には輸出できないホタテが大量にあります。\n　森町は、申し出があった全国の学校に給食で使ってもらおうと、国の基金を財源に10万食分を無償で提供する方針です。\n\n森町　岡嶋康輔町長\n「冷凍がいっぱいいっぱいになるということは、冷凍庫を使って在庫を回すという作業ができなくなっている。事業者に先行きの見える施策を打って行かないと」\n\n　森町は、来月の議会に提案し、可決されれば年内にも発送する考えです。",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "TBS NEWS DIG,北海道放送",
      media: "https://newsdig.ismcdn.jp/mwimgs/2/0/-/img_203d39e555c0686d3ca5f9a6b91b6dff141610.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "7c6c1ded980ee0eb6e3a12174a9819c8"
    },
    {
      title: "ブロードウェイミュージカル『ジャニス・ジョプリン』無料初放送　BS松竹東急で10月8日",
      author: "日曜ゴールデンシアター",
      published_date: "2023-09-25 16:43:00",
      published_date_precision: "timezone unknown",
      link: "https://amass.jp/169934/",
      clean_url: "amass.jp",
      excerpt: "ジャニス・ジョプリンの姿を描いたブロードウェイミュージカル『ジャニス・ジョプリン』が無料初放送決定。BS松竹東急で10月8日(日) に放送されます。ジャニス・ジョプリン役は歌手・女優のメアリー・ブリジット・デイヴィス",
      summary: "2023/09/25 16:43掲載\n \n「ジャニス・ジョプリン」　©Jason Niedle\n \nジャニス・ジョプリン（Janis Joplin）\nの姿を描いたブロードウェイミュージカル『ジャニス・ジョプリン』が無料初放送決定。BS松竹東急で10月8日(日) に放送されます。ジャニス・ジョプリン役は歌手・女優のメアリー・ブリジット・デイヴィスで、トニー賞ミュージカル部門最優秀主演女優賞にノミネートされています。",
      rights: "Copyright amass",
      rank: 235323,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "ジャニス ジョプリン,日曜ゴールデンシアター",
      media: "https://amassing2.sakura.ne.jp/image/jacket/300/2023b/131012.jpg",
      is_opinion: false,
      twitter_account: "@amass_jp",
      _score: null,
      _id: "ccb115c272805f9824bdec797961206b"
    },
    {
      title: "高速道路でトラック炎上　タイヤ付近から出火、男性運転手にけがなく巻き込まれた車なし　道央自動車道に通行止めなど交通規制",
      author: "北海道放送",
      published_date: "2023-09-25 16:43:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/741575?display=1",
      clean_url: "tbs.co.jp",
      excerpt: "25日、北海道内では交通事故が相次ぎました。　札幌市の道央道ではトラックが炎上し、一部が通行止めになっています。　立ち上る真っ赤な炎と黒い煙。　警察によりますと、午後１時ごろ、札幌市白石区流通センター… (1ページ)",
      summary: "25日、北海道内では交通事故が相次ぎました。\n　札幌市の道央道ではトラックが炎上し、一部が通行止めになっています。\n\n　立ち上る真っ赤な炎と黒い煙。\n　警察によりますと、午後１時ごろ、札幌市白石区流通センター５丁目付近の道央自動車道の下りで走っていた７トントラックのタイヤ付近から火が出ました。\n　男性運転手にけがはなく、巻き込まれた車もいません。\n　火事の影響で、道央道の札幌南インターから大谷地インターの札幌方向が通行止めになっています。\n\n　また、午後０時半ごろ、後志の喜茂別町の中山峠に近い国道230号線では、乗用車が中央分離帯にぶつかり、運転していた70代の男性が意識不明の重体です。\n\n　仁木町の道道では、左折待ちのトラックに自転車が追突し、自転車に乗っていた20代の男性が首の痛みなどを訴えて病院で手当てを受けています。\n\n【通行止め】（25日午後４時半時点）\n道央道：札幌南インター⇒大谷地インター、北広島インター（入口閉鎖）",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "TBS NEWS DIG,北海道放送",
      media: "https://newsdig.ismcdn.jp/mwimgs/9/1/-/img_91db83ee96c5315496458bd02936a263135749.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "9dd1b9dd82219b4ef0b0f7a52c7ab38e"
    },
    {
      title: "「ハワイまで1万5000円」JAL系LCC「ZIPAIR」が破格の運賃が提示 (2023年9月25日掲載)",
      author: "乗りものニュース",
      published_date: "2023-09-25 16:42:00",
      published_date_precision: "timezone unknown",
      link: "https://news.livedoor.com/topics/detail/25051167",
      clean_url: "livedoor.com",
      excerpt: "JALグループの国際線LCC「ZIPAIR」が特別セールを10月4日まで実施中だ。提供座席に限りがあるものの展開する全路線が対象で、破格の運賃に。ホノルル線が片道1万5000円、LA・サンフランシスコ線が同3万5000円となる",
      summary: "",
      rights: "livedoor.com",
      rank: 3444,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "乗りものニュース",
      media: "https://image.news.livedoor.com/newsimage/stf/e/c/ecd98_1438_10cdf7871cf0dce4ed10f6e81bff38c9.jpg",
      is_opinion: false,
      twitter_account: "@livedoornews",
      _score: null,
      _id: "785b2a1d367eb6cbef385c02fefefb2c"
    },
    {
      title: "所属アーティスト総勢23名が集結「BMSG FES'23」東京公演開催",
      author: "",
      published_date: "2023-09-25 16:41:00",
      published_date_precision: "timezone unknown",
      link: "https://rollingstonejapan.com/articles/detail/40049",
      clean_url: "rollingstonejapan.com",
      excerpt: "SKY-HI率いるマネジメント／レーベル・BMSGの所属アーティスト総勢23名が集結する音楽フェス「BMSG FES'23」が、9月23日（土）、9月24日（日）、東京体育館にて開催された。関連記事：BE:FIRSTが語る「Ma",
      summary: "SKY-HI率いるマネジメント／レーベル・BMSGの所属アーティスト総勢23名が集結する音楽フェス「BMSG FES'23」が、9月23日（土）、9月24日（日）、東京体育館にて開催された。\n関連記事：\n\n2023年の本年は東京、大阪と2都市開催。BE:FIRSTをはじめとするBMSG所属のメンバー23名がグループの垣根を越え、BMSG EAST、BMSG WESTに別れて特別ユニットを結成。それぞれの新曲「The Sun from the EAST」「The Moon in the WEST」を初披露した。各アーティストも熱いパフォーマンスを繰り広げ、SKY-HI「Sarracenia」、BE:FIRST「Boom Boom Back」、MAZZEL「Carnival」などを披露。9月30日、10月1日には大阪城ホールにて開催される。\nBMSG公式ホームページ：\nhttps://bmsg.tokyo/\n \n \n \n \n \n \n無料メールマガジン会員登録に登録すると、\n続きをお読みいただけます。\n \n \n無料のメールマガジン会員に登録すると、\nすべての記事が制限なく閲覧でき、記事の保存",
      rights: "rollingstonejapan.com",
      rank: 211861,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "",
      media: "https://images.rollingstonejapan.com/articles/40000/40049/OG/d93ca3bf0dd85b07273f1335de4d2a34.jpg",
      is_opinion: false,
      twitter_account: "@rollingstonejapan",
      _score: null,
      _id: "0c76897975a2b268a2dbaaf1c6bbd548"
    },
    {
      title: "ハミルトン、不満を示しつつも僚友を支援、5位も守る「チームのためフェラーリに勝つことが重要だった」F1日本GP",
      author: "t web 編集部",
      published_date: "2023-09-25 16:40:36",
      published_date_precision: "timezone unknown",
      link: "https://www.as-web.jp/f1/994725",
      clean_url: "as-web.jp",
      excerpt: "2023年F1日本GP決勝で、メルセデスのルイス・ハミルトンは5位を獲得した。 ハミルトンはスタート直後にセルジオ・ペレス（レッドブル）との接触があり、ウイングに小さなダメージを負い、順位もひとつ落としたが、ペレスの後退により7番手に戻った。序盤、チームメイトのジョージ・ラッセルと激しくバトル、前の位置を維持したハミルトンだが、さらに約10周後、ラインがふくらんだことでラッセルに追いつかれ、再",
      summary: "0年日本GP決勝で、メルセデスのルイス・ハミルトンは位を獲得した。\n\nハミルトンはスタート直後にセルジオ・ペレス（レッドブル）との接触があり、ウイングに小さなダメージを負い、順位もひとつ落としたが、ペレスの後退により番手に戻った。序盤、チームメイトのジョージ・ラッセルと激しくバトル、前の位置を維持したハミルトンだが、さらに約0周後、ラインがふくらんだことでラッセルに追いつかれ、再びバトルに。ハミルトンはポジションを守るなかでラッセルをコース外に押し出す形になり、この一件は記録されたが、ペナルティは科されなかった。",
      rights: "as-web.jp",
      rank: 70381,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "t web 編集部",
      media: "https://cdn-image.as-web.jp/2023/09/25160456/asimg_23R17JapanSu-Ham-Merc1_6165113117e1f9a-1280x853.jpg",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "202fec4f00b01526925cd9cafba63890"
    },
    {
      title: "希少植物'タヌキアヤメ' 北限の福江島で黄色い花を咲かせる",
      author: "長崎放送",
      published_date: "2023-09-25 16:39:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/741222",
      clean_url: "tbs.co.jp",
      excerpt: "長崎県の天然記念物にも指定されている希少植物『タヌキアヤメ』が、小さな黄色い花を咲かせています。福江島を北限とする『タヌキアヤメ』。親指程の小さな花です。五島市岐宿町では、自生した50株程が農地整備に… (1ページ)",
      summary: "長崎県の天然記念物にも指定されている希少植物『タヌキアヤメ』が、小さな黄色い花を咲かせています。\n\n福江島を北限とする『タヌキアヤメ』。親指程の小さな花です。\n五島市岐宿町では、自生した50株程が農地整備に伴い、田んぼの跡地に植え替えられていて、住民達が成長を見守っています。\n\n『タヌキアヤメ』を管理している中村 利夫さん（74）：\r\n「アヤメを想像したところが、似ても似つかない小さな花が咲いていた。\r\n'化かされた'（と思ったのが名前の由来）という説もありますね」\n\n'タヌキの様な毛'と'アヤメの様な葉'から名前が付いたとも言われています。\nことしは例年より大きく育ち、高さ2m程に成長しています。\n\n長崎県の天然記念物『タヌキアヤメ』は、今週いっぱい花を咲かせるということです。",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "TBS NEWS DIG,長崎放送",
      media: "https://newsdig.ismcdn.jp/mwimgs/b/f/-/img_bfc459f1c582de0caff12f7afb92c405209392.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "cf071936db6b5e7cca3ccaab18bc64fc"
    },
    {
      title: "クモの巣状にガラスにひびが…　山間の小学校にクマが現れ被害　教職員、児童にけがなし　岩手・八幡平市",
      author: "IBC岩手放送",
      published_date: "2023-09-25 16:37:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/741557",
      clean_url: "tbs.co.jp",
      excerpt: "25日午前、岩手県八幡平市の小学校で窓ガラスにひびが入っているのが見つかりました。付近にはクマのものとみられる足跡が残されていて、警察が注意を呼び掛けています。被害があったのは八幡平市立寄木小学校です… (1ページ)",
      summary: "25日午前、岩手県八幡平市の小学校で窓ガラスにひびが入っているのが見つかりました。付近にはクマのものとみられる足跡が残されていて、警察が注意を呼び掛けています。\n\r\n被害があったのは八幡平市立寄木小学校です。岩手警察署によりますと25日午前7時半ごろ、校舎1階の窓ガラスにひびが入っているのに職員が気づき、警察に通報しました。22日午後4時40分ごろから25日午前7時半ごろの間に被害にあったものとみられています。この期間学校は休みで、児童の出入りはありませんでした。窓ガラスは縦133センチ、横85センチで、地上から90センチの所にあり、ひびはクモの巣状にガラスの下部に入っていました。23日午後1時半には校庭でクマが目撃されていました。",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "IBC岩手放送,TBS NEWS DIG",
      media: "https://newsdig.ismcdn.jp/mwimgs/c/8/-/img_c8515a0a04ca255c14cc940f981e9c1f434372.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "fd616ef8b1c3e7834a1e6bc7361628f1"
    },
    {
      title: "『ベヨネッタ』『The Wonderful 101』などで知られるゲームデザイナー神谷英樹氏がプラチナゲームズを退社",
      author: "RIKUSYO",
      published_date: "2023-09-25 16:37:00",
      published_date_precision: "timezone unknown",
      link: "https://www.gamespark.jp/article/2023/09/25/134452.html",
      clean_url: "gamespark.jp",
      excerpt: "「自分自身の信念に基づいて考え抜いた結果、これが最良だという結論に至りました」",
      summary: "『ベヨネッタ』シリーズや『The Wonderful 101』どで知られるゲームデザイナーの\n神谷英樹\n氏が、10月12日をもってプラチナゲームズを退社することを発表しました。\n公式Xアカウントでは「簡単な決断ではありませんでしたが、自分自身の信念に基づいて考え抜いた結果、これが最良だという結論に至りました。これからも変わらず、自分らしい物作りを目指して参ります。是非お楽しみに」と語っています。\nまた、プラチナゲームズ公式Xアカウントでも同様の発表が行われており、「プラチナゲームズの立ち上げから今日に至るまで、独創的なアイデアやリーダーシップを発揮し、我々の成長に貢献してくれたことを感謝しています。これからも彼のクリエイターとしての挑戦が成功すると信じていますし、共にゲーム業界全体を盛り上げていければと考えております」と神谷氏へのメッセージを伝えています。\n\n\n\n\n《RIKUSYO》",
      rights: "gamespark.jp",
      rank: 15919,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "RIKUSYO",
      media: "https://www.gamespark.jp/imgs/ogp_f/724685.jpg",
      is_opinion: false,
      twitter_account: "@gamespark",
      _score: null,
      _id: "ebb8d633cfff04dcdc9504272304f2eb"
    },
    {
      title: "ジャニーズに社名変更要請",
      author: "",
      published_date: "2023-09-25 16:37:00",
      published_date_precision: "timezone unknown",
      link: "https://www.shimotsuke.co.jp/articles/-/794659",
      clean_url: "shimotsuke.co.jp",
      excerpt: "ジャニーズ事務所の性加害問題を巡り、日本テレビの石沢顕社長は２５日の定例記者会見で、同事務所に社名変更を検討するよう２０日に申し入れたと明らかにした。所属タレントのマネジメントと被害者の補償を行う組織の分離を検討することも要請した。…",
      summary: "ジャニーズ事務所の性加害問題を巡り、日本テレビの石沢顕社長は２５日の定例記者会見で、同事務所に社名変更を検討するよう２０日に申し入れたと明らかにした。所属タレントのマネジメントと被害者の補償を行う組織の分離を検討することも要請した。\n\n\n　石沢社長は会見で、同事務所が既に発表している対応策について「私たちとしてはまだ十分とは受け止めていない」と発言。申し入れ書では、実効性ある被害者救済の実施のほか、所属タレントが活動しやすい環境整備などを求めた。事務所側に渡した際に、社名変更などの検討要請も口頭で伝えたという。\n\n\n　一方、所属タレントの番組出演については「現時点でキャスティングを変更する考えはない」と説明。ただ、同事務所は１０月２日に具体的な対応策を公表するとしており「信頼を得られるような今後の方針を打ち出せるかがポイント。タレント起用はスポンサーの考えも参考にしながら適切に判断したい」と述べた。",
      rights: "shimotsuke.co.jp",
      rank: 21874,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "",
      media: "https://soon.ismcdn.jp/mwimgs/a/5/1200wm/img_a5ce4304fef12adb8518ee80b40796f048171.jpg",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "4f1f115991deb634242820f39c0fbe74"
    },
    {
      title: "「お前の家族殺す」「指を詰めろ」１８歳知人への暴行・脅迫で広島市の男起訴　鹿児島",
      author: "南日本放送",
      published_date: "2023-09-25 16:36:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/741535",
      clean_url: "tbs.co.jp",
      excerpt: "鹿児島市で１８歳の知人男性を１２時間に渡って暴行した上に、「裏切ったらお前の家族を殺す」などと脅迫したとして、広島市の２４歳の男が起訴されました。暴行・脅迫の罪で起訴されたのは、広島市の無職・山… (1ページ)",
      summary: "鹿児島市で１８歳の知人男性を１２時間に渡って暴行した上に、「裏切ったらお前の家族を殺す」などと脅迫したとして、広島市の２４歳の男が起訴されました。\n\n暴行・脅迫の罪で起訴されたのは、広島市の無職・山田郁哉被告（２４）です。\n\n起訴状などによりますと、山田被告は今年６月３０日夜から翌朝までのおよそ１２時間の間に、鹿児島市内の公園などで１８歳の知人男性を平手やこぶしで複数回殴ったとされています。\n\nさらに、被告は男性に対し、「裏切ったらお前の家族を殺す」と脅したり、被告の自宅で包丁とまな板を置いた状態で「指を詰めろ」と脅迫したということです。\n\n被害届を受けた警察が、聞き込みや防犯カメラの映像をもとに山田被告を特定し、今月１日に逮捕していました。\n\n逮捕当時の山田被告の認否について警察は「捜査に支障がある」として明らかにしておらず、今後、刑事裁判で審理されることになります。",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "TBS NEWS DIG,南日本放送",
      media: "https://newsdig.ismcdn.jp/mwimgs/a/4/-/img_a41993d9f734f3c4f6fd5b7ddd161a36503000.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "5b194d4ef7005fcaf9a61aafc43123b1"
    },
    {
      title: "1Password、iOS版でパスキー対応　Androidも対応へ",
      author: "",
      published_date: "2023-09-25 16:35:00",
      published_date_precision: "timezone unknown",
      link: "https://www.itmedia.co.jp/news/articles/2309/25/news138.html",
      clean_url: "itmedia.co.jp",
      excerpt: "パスワード管理ツールの定番「1Password」のiOS版が、パスワードレス認証「パスキー」に対応した。",
      summary: "パスワード管理ツールの定番「1Password」のiOS版（iOS 17）が、パスワードレス認証「パスキー」に対応した。事前に設定しておけば、生体認証などで1Passwordにログインでき、複数のパスワードをより簡便に管理できる。\n\n\n　6月からβ対応していたWebブラウザ版でも正式にパスキー対応した。Android版も提供準備ができており、近日中にAndroid 14で利用できるようになる予定だ。\n\n\n\n\n\n\n\n\n　パスキーは、事前に設定しておくことで、パスワード入力不要でログインでき、不正ログイン対策にもなるセキュアな認証方式。スマートフォンなどのユーザー端末で鍵ペアを生成。アプリやサーバには公開鍵を、デバイス側には秘密鍵を安全に格納し、ログイン時に指紋などデバイス側の生体認証で秘密鍵を取り出して鍵ペアで認証する。\n\n\n\n\n\n\n1Password、「パスキー」をサポート　主要ブラウザのβ版拡張機能で\n\nサブスク制パスワード管理ツールの1Passwordは、Webブラウザでの「パスキー」サポートを開始した。Chrome、Edge、Safari、Firefox、Braveにβ版の拡張機能",
      rights: "itmedia.co.jp",
      rank: 3371,
      topic: "tech",
      country: "JP",
      language: "ja",
      authors: "",
      media: "https://image.itmedia.co.jp/news/articles/2309/25/cover_news138.jpg",
      is_opinion: false,
      twitter_account: "@itmedia_news",
      _score: null,
      _id: "549803f0301e0157d32b26322609011a"
    },
    {
      title: "自民・小島敏文氏「次回の衆院選は小選挙区1本で」 比例に重複立候補しない考え明らかに　広島5区",
      author: "中国放送",
      published_date: "2023-09-25 16:33:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/741532",
      clean_url: "tbs.co.jp",
      excerpt: "次の衆議院選挙で広島5区から立候補を予定している自民党の小島敏文衆院議員（73）は、比例代表で重複立候補しない考えを明らかにしました。自民党 小島敏文衆院議員（比例中国）「私はもう次回の衆議院選挙では… (1ページ)",
      summary: "次の衆議院選挙で広島5区から立候補を予定している自民党の小島敏文衆院議員（73）は、比例代表で重複立候補しない考えを明らかにしました。\n自民党　小島敏文衆院議員（比例中国）\r\n「私はもう次回の衆議院選挙では、比例区は出ません。小選挙区1本で行きます」\n自民党の小島敏文氏は尾道市で開いた後援会の集会でこのように述べ、次の衆議院選挙では、比例代表中国ブロックに重複立候補しない考えを明らかにしました。小島氏は前回、立憲民主党の佐藤公治氏（64）に敗れるなど、旧広島6区で5連敗していて、過去の当選4回はいずれも比例での復活でした。\n小島氏\r\n「いつまでも比例区じゃないって言ってるでしょ。やはり政治家である以上、小選挙区で通りたいよね」\n旧広島6区は小選挙区の区割り変更によって、三原市本郷町や大和町、尾道市瀬戸田町を加えた5区となっています。\n\n広島5区には、▽立憲民主党・現職の佐藤公治氏、▽共産党・新人の猪原真弓氏（62）も立候補を予定しています。",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "TBS NEWS DIG,中国放送",
      media: "https://newsdig.ismcdn.jp/mwimgs/2/2/-/img_2228fb03029b1acbf36eee1b7515b528156333.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "b27b2dd8a3f4ce478b4bb15bbc8088fe"
    },
    {
      title: "Pierre Fabre LaboratoriesとVernalisが腫瘍向け創薬で提携を発表",
      author: "",
      published_date: "2023-09-25 16:32:00",
      published_date_precision: "timezone unknown",
      link: "https://www.shimotsuke.co.jp/articles/-/794664",
      clean_url: "shimotsuke.co.jp",
      excerpt: "【画像：https://kyodonewsprwire.jp/img/202309250111-O1-s6B9A091】カストル（フランス）、ケンブリッジ（英国）2023年9月25日 【PR Newswire＝共同通信JBN】Pierre Fabre Laboratories（ピエール・ファーブル・ラボラトリーズ）とHitGen…",
      summary: "【画像：\nhttps://kyodonewsprwire.jp/img/202309250111-O1-s6B9A091\n】 カストル（フランス）、ケンブリッジ（英国）2023年9月25日 【PR Newswire＝共同通信JBN】Pierre Fabre Laboratories（ピエール・ファーブル・ラボラトリーズ）とHitGen Inc.の完全子会社Vernalis（R&D）Ltd（「Vernalis」）は、複数のがんをターゲットとする前臨床候補化合物を同定するため、長期パートナーシップを締結したと発表しました。     契約条件に基づき、Vernalisはその専門知識を生かし、明らかにされていない標的ポートフォリオに対する創薬を可能にし、フラグメント手法および構造ベース手法により、その活性を調節する低分子を同定します。本研究は、Pierre Fabre Laboratoriesの腫瘍領域での経験と組み合わされ、Pierre Fabre Laboratoriesがさらなる開発・商品化を目指すさまざまながん治療薬候補を同定していきます。Pierre Fabre Laboratorie",
      rights: "shimotsuke.co.jp",
      rank: 21874,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "",
      media: "https://soon.ismcdn.jp/mwimgs/f/a/1200wm/img_facd17e8b4592573c1824b86f4adfcab16198.jpg",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "926067e8ff752472518f39aff910587a"
    },
    {
      title: "動き出したトラック止めようと・・・　トラックのドアにはさまれ男性死亡",
      author: "テレビ高知",
      published_date: "2023-09-25 16:32:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/741529",
      clean_url: "tbs.co.jp",
      excerpt: "24日夜、高知県土佐市の市道で、64歳の男性がトラックの運転席のドアに挟まれて死亡しているのが見つかりました。止めたはずのトラックが坂道を下り始めたため、運転席に乗り込んでブレーキをかけようとしていたと… (1ページ)",
      summary: "24日夜、高知県土佐市の市道で、64歳の男性がトラックの運転席のドアに挟まれて死亡しているのが見つかりました。止めたはずのトラックが坂道を下り始めたため、運転席に乗り込んでブレーキをかけようとしていたと見られます。\n事故があったのは土佐市宮ノ内の市道です。警察と消防によりますと24日夜8時前、「トラックと建物の間に男性が挟まれている。意識と呼吸がない」と消防に通報がありました。\n消防がかけつけると、近くに住む三宮浩さんが、トラックの運転席のドアに挟まれていて、その場で死亡が確認されました。\n警察によりますと、三宮さんは坂道の上にトラックを停車。作業のためトラックを降りたところ、何らかの原因でトラックが坂道を下り始めたということです。三宮さんは運転席に乗り込んでブレーキをかけようとしましたが、坂道を下ったトラックが建物に接触して運転席のドアが閉まり、挟まれたと見られます。\n警察が詳しい経緯を調べています。",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "TBS NEWS DIG,テレビ高知",
      media: "https://newsdig.ismcdn.jp/mwimgs/b/2/-/img_b22c6f93b12b1560df1bcd95ddf99008310905.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "d02ab484db2436c319b1d02ac3cea7c4"
    },
    {
      title: "沿岸被災地「一日も早く訪れたい」　土屋品子復興大臣が就任後初の岩手県入り　達増知事と面談",
      author: "IBC岩手放送",
      published_date: "2023-09-25 16:31:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/741516",
      clean_url: "tbs.co.jp",
      excerpt: "土屋品子復興大臣が25日、就任後初めて岩手県内を訪問し、県庁で達増知事と意見交換しました。大臣は「現場主義に徹して皆さんの意見を聞く」と意気込みを語りました。土屋大臣は13日に発足した岸田改造内閣で初入… (1ページ)",
      summary: "土屋品子復興大臣が25日、就任後初めて岩手県内を訪問し、県庁で達増知事と意見交換しました。大臣は「現場主義に徹して皆さんの意見を聞く」と意気込みを語りました。\n土屋大臣は13日に発足した岸田改造内閣で初入閣しました。25日は同じく就任した高木宏壽副大臣、平沼正二郎政務官とともに県庁を訪れ、達増知事と被災地のコミュニティ支援やなりわいの再生について意見を交わしました。\n\r\n（土屋復興大臣）\r\n「司令塔としてさまざまな省に要望をつないでいきたい。みなさんの要望を受け止められるようにしたい」\n\r\n達増知事は福島第一原発の処理水の海洋放出に伴う地元への支援や風評被害対策などを訴えました。また土屋大臣は岩手県沿岸の被災地訪問について「一日も早く訪れたい」と述べました。",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "IBC岩手放送,TBS NEWS DIG",
      media: "https://newsdig.ismcdn.jp/mwimgs/e/c/-/img_ec95dcd4ba28c338ede751a3f27334ac143939.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "248314b8a268158223694a8da12e448d"
    },
    {
      title: "乗用車が車線変更しようとしたところ市バスと接触　乗客3人が軽傷",
      author: "CBCテレビ",
      published_date: "2023-09-25 16:31:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/741497",
      clean_url: "tbs.co.jp",
      excerpt: "名古屋市瑞穂区で市バスと乗用車が衝突。乗客3人が軽傷です。事故があったのは、瑞穂区豊岡通の片側2車線の市道で、警察によりますと25日午前9時ごろ、右側の車線を走っていた乗用車が車線変更したところ、左側を… (1ページ)",
      summary: "名古屋市瑞穂区で市バスと乗用車が衝突。乗客3人が軽傷です。\n\r\n事故があったのは、瑞穂区豊岡通の片側2車線の市道で、警察によりますと25日午前9時ごろ、右側の車線を走っていた乗用車が車線変更したところ、左側を走っていた金山発・瑞穂運動場東行きの市バスの前方に衝突しました。\n\nこのバスは当時、乗客と運転手のあわせて5人が乗っていて、このうち乗客の54歳から76歳の男女3人が軽いケガをしました。乗用車を運転していたのは67歳の大学職員で、ケガの有無は分かっていません。\n\r\n警察は乗用車の車線変更が事故に繋がったとみて当時の状況や事故の原因を調べています。",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "CBCテレビ,TBS NEWS DIG",
      media: "https://newsdig.ismcdn.jp/mwimgs/7/4/-/img_741f845a27c36a516b44874ab1797a0f173654.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "d52d57f3790f4bf9fe9f6703973ef0dd"
    },
    {
      title: "「ドライバーの残業時間は年1300時間以上も…」迫る'2024年問題' 荷台だけ輸送で運転時間が半分に?!",
      author: "あいテレビ",
      published_date: "2023-09-25 16:30:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/739165",
      clean_url: "tbs.co.jp",
      excerpt: "物流業界に'2024年問題'と呼ばれるトラックドライバー不足の危機が迫っています。この問題を解決する1つの手段として注目されているのが愛媛県四国中央市で運用が進む「RO-RO（ローロー）船」という船です。果た… (1ページ)",
      summary: "物流業界に'2024年問題'と呼ばれるトラックドライバー不足の危機が迫っています。\nこの問題を解決する1つの手段として注目されているのが愛媛県四国中央市で運用が進む「RO-RO（ローロー）船」という船です。果たして物流業界の'救世主'となれるのでしょうか？\n\n愛媛県四国中央市の大王海運が運航している「RO-RO船」。\n千葉の港を出発し、岡山の宇野港に立ち寄りました。RO-RO船に乗って運ばれてきたのは「トレーラーシャーシ」と呼ばれるトラックの荷台部分だけ。船にトラックのドライバーは乗っていません。\n\n＜大王海運・曽我部雅司 社長＞\r\n「車のタイヤが転がって船に乗る、これを『ROLE ON（ロールオン）』と言います。今度はタイヤが転がって船から降りてくる、これが『ROLE OFF（ロールオフ）』と言います。この2つを合わせて『RO-RO（ローロー）船』と呼んでいます」\n港に着くと、荷台は牽引車につながれて船から降ろされ、そのまま配達先へと運ばれます。そして、宇野港で新たな荷台が運び込まれたRO-RO船はおよそ2時間半かけて愛媛の三島川之江港へ向かいます。\n\n大王海運ではRO-RO船を3隻",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "TBS NEWS DIG,あいテレビ",
      media: "https://newsdig.ismcdn.jp/mwimgs/5/c/-/img_5c49f2b1b11943ef9839056a32794bba97662.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "4e1627fc06c0b57755fac41123f96871"
    },
    {
      title: "重度の知的障害がある長男を殺害した罪に問われている母親の裁判員裁判　検察は懲役8年を求刑【岡山】",
      author: "RSK山陽放送",
      published_date: "2023-09-25 16:30:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/741214",
      clean_url: "tbs.co.jp",
      excerpt: "子育てへの不安などから重度の知的障害がある長男を殺害した罪に問われている母親の裁判員裁判で、検察は懲役8年を求刑しました。殺人の罪に問われているのは岡山県和気町のパート従業員・藤井典子被告です。起訴… (1ページ)",
      summary: "子育てへの不安などから重度の知的障害がある長男を殺害した罪に問われている母親の裁判員裁判で、検察は懲役8年を求刑しました。\n\n殺人の罪に問われているのは岡山県和気町のパート従業員・藤井典子被告です。起訴状などによりますと藤井被告は昨年6月、実家の駐車場にとめた車の中で長男・蒼天くんの首をタオルで絞めて殺害した罪に問われています。\n\nきょう（25日）開かれた裁判員裁判で検察側は、夫が子育てに協力しないことに絶望し息子を心中に巻き込んだことは極めて短絡的かつ身勝手であるなどと指摘し、懲役8年を求刑しました。\n\n一方、弁護側は夫から見放されたことによる極度のストレスやうつ病によって心神耗弱状態だったとして、最長で3年の懲役と執行猶予を求めました。\n判決は来月（10月）3日に言い渡される予定です。",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "RSK山陽放送,TBS NEWS DIG",
      media: "https://newsdig.ismcdn.jp/mwimgs/7/e/-/img_7e1950ace34938162b60d63c7bac3b69150031.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "5bc46b2e8eb260c1c53b5b3b9cf2b176"
    },
    {
      title: "使われなくなった人形やぬいぐるみに別れを告げる「人形供養祭」",
      author: "宮崎放送",
      published_date: "2023-09-25 16:30:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/741520",
      clean_url: "tbs.co.jp",
      excerpt: "使われなくなった人形やぬいぐるみに別れを告げる「人形供養祭」が宮崎市でありました。これは、「家族葬のファミーユ」が、人形やぬいぐるみを処分する際に、感謝の気持ちを込めてお別れをしてもらおうと開いたも… (1ページ)",
      summary: "使われなくなった人形やぬいぐるみに別れを告げる「人形供養祭」が宮崎市でありました。\n\r\nこれは、「家族葬のファミーユ」が、人形やぬいぐるみを処分する際に、感謝の気持ちを込めてお別れをしてもらおうと開いたものです。\n\r\n祭壇には、長年使われてきた人形やぬいぐるみが並べられ、訪れた家族連れなどが静かに手を合わせていました。\n\r\n「家族葬のファミーユ」が人形供養を行うのは3年ぶりとなっていて、今後も要望があれば、実施したいとしています。",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "TBS NEWS DIG,宮崎放送",
      media: "https://newsdig.ismcdn.jp/mwimgs/5/9/-/img_593bb55f311c8df8d080a9c4e35a60c3311395.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "03b97e21b47705487d49135e793b500a"
    },
    {
      title: "「暴力団を根絶やしにするのは健全な社会ではない」井本英雄県議　発言の取り消しを申し出て認められる",
      author: "宮崎放送",
      published_date: "2023-09-25 16:30:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/741485",
      clean_url: "tbs.co.jp",
      excerpt: "9月21日の宮崎県議会で暴力団に関する発言をした井本英雄県議が、25日、発言の取り消しを申し出ました。この申し出は認められたため、会議録から削除される見通しです。井本英雄県議は、9月21日に開かれた文教警察… (1ページ)",
      summary: "9月21日の宮崎県議会で暴力団に関する発言をした井本英雄県議が、25日、発言の取り消しを申し出ました。\r\nこの申し出は認められたため、会議録から削除される見通しです。\n\r\n井本英雄県議は、9月21日に開かれた文教警察企業常任委員会で、「暴力団を根絶やしにするのはある意味健全な社会ではない」との旨を発言。\n\r\n一方、県警察本部では、「社会全体の問題として、官民一体となって暴力団排除に取り組んでいる」としていて、井本県議の発言が波紋を呼んでいました。\n\r\nこうしたなか、25日に開かれた文教警察企業常任委員会で、井本県議は、発言の取り消しを申し出て、全会一致で認められました。\n\r\n県議会事務局によりますと、井本県議の発言は、条例に基づき会議録から削除されるということです。",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "TBS NEWS DIG,宮崎放送",
      media: "https://newsdig.ismcdn.jp/mwimgs/4/9/-/img_494f22c2db0a09e744e807fbb33d21d5215589.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "602e4dcdf61435da24410877469370dd"
    },
    {
      title: "恐喝未遂の疑いで逮捕・起訴された倉敷市議会議員への対応協議する特別委員会　本人に証言や弁明の機会を設ける方針【岡山】",
      author: "RSK山陽放送",
      published_date: "2023-09-25 16:30:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/740997",
      clean_url: "tbs.co.jp",
      excerpt: "恐喝未遂の疑いで逮捕・起訴された塩津学倉敷市議会議員への対応を決めるため、倉敷市議会は1回目となる特別委員会を開きました。倉敷市議会で開かれた1回目の特別委員会には7人の議員が出席し、委員長の選任や今… (1ページ)",
      summary: "恐喝未遂の疑いで逮捕・起訴された塩津学倉敷市議会議員への対応を決めるため、倉敷市議会は1回目となる特別委員会を開きました。\n\n倉敷市議会で開かれた1回目の特別委員会には7人の議員が出席し、委員長の選任や今後の運営について話し合いました。\n\nこの特別委員会は市の議員政治倫理条例に基づき、恐喝未遂の容疑で逮捕・起訴された塩津議員が倫理基準に違反していないかを審査するもので、今後、塩津議員本人にも証言や弁明の機会を設ける方針を決めました。\n（委員長に選ばれた 藤井昭佐倉敷市議）「（塩津議員）本人が話せる、聞き取りができる状況になってきたら、全議員でしっかり状況を共有しながら、この条例に則って進められたらなと思います」\n次回の開催は未定ですが、特別委員会では市民の信頼回復に向けて審査したいとしています。",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "RSK山陽放送,TBS NEWS DIG",
      media: "https://newsdig.ismcdn.jp/mwimgs/5/2/-/img_52f0cbb91015cb73728fbec44ad6de1133827.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "c7fe34e425c082115ed6920d4b97b4ee"
    },
    {
      title: "地権者に配布すべき通知書を13年間放置　日向市で不適切な事務処理が発覚",
      author: "宮崎放送",
      published_date: "2023-09-25 16:30:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/741511",
      clean_url: "tbs.co.jp",
      excerpt: "宮崎県日向市は、土地区画整理事業に伴い、地権者に配布すべき「登記識別情報通知書」を13年間放置していたことを明らかにしました。日向市によりますと、この問題は、市が1996年度から行った土地区画整理事業で、… (1ページ)",
      summary: "宮崎県日向市は、土地区画整理事業に伴い、地権者に配布すべき「登記識別情報通知書」を13年間放置していたことを明らかにしました。\n\r\n日向市によりますと、この問題は、市が1996年度から行った土地区画整理事業で、土地の区分などが変更された場合に地権者に配布する「登記識別情報通知書」を渡していなかったものです。\n\r\n通知書は、62人の地権者が配布対象となっていて、このうち48人については、問題が発覚する8月下旬までおよそ13年間放置されていました。\n\r\n現在、市では、通知書を配布するとともに、地権者に謝罪しています。",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "TBS NEWS DIG,宮崎放送",
      media: "https://newsdig.ismcdn.jp/mwimgs/1/7/-/img_1786b7cb938bf7801a038cd2e2efc45e330069.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "412c1970d6f972ba3cd991c4afa7ad87"
    },
    {
      title: "軽トラックを暴走させた中国籍の男　初公判で起訴内容認める　検察は懲役2年を求刑",
      author: "宮崎放送",
      published_date: "2023-09-25 16:30:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/741473?display=1",
      clean_url: "tbs.co.jp",
      excerpt: "今年2月、軽トラックを男女に衝突させ暴行などの罪に問われている中国籍の男の初公判が宮崎地裁で開かれ、男は「間違いありません」と起訴内容を認めました。起訴されているのは、札幌市の廃品回収業、刘国慶（り… (1ページ)",
      summary: "今年2月、軽トラックを男女に衝突させ暴行などの罪に問われている中国籍の男の初公判が宮崎地裁で開かれ、男は「間違いありません」と起訴内容を認めました。\n\r\n起訴されているのは、札幌市の廃品回収業、刘国慶（りゅうこくけい）被告(42歳)です。\n\r\n起訴状などによりますと、刘被告は、今年2月、都城市で自身が運転する軽トラックを男女2人に衝突させけがを負わせるなどした暴行と傷害の罪や、パトカーに軽トラを衝突させた公務執行妨害の罪に問われています。\n\r\n宮崎地裁で開かれた25日の初公判で、刘被告は「間違いありません」と起訴内容を認め、検察側は、「生命にもかかわりかねない危険な犯行であり悪質」などとし、懲役2年を求刑しました。\n\r\nこれに対し、弁護側は、「精神障害で明確な記憶がないが、事実を認め、深く反省している」などと述べ、執行猶予付きの判決を求めました。\n\r\n裁判は即日結審し、10月13日に判決が言い渡されます。",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "TBS NEWS DIG,宮崎放送",
      media: "https://newsdig.ismcdn.jp/mwimgs/3/2/-/img_32babc4c475d482ac4e0f2343f5308b5243767.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "149a43f9e79b3f74e9e77845a659e7f7"
    },
    {
      title: "土木工事会社が社債を活用して学校に測量道具を贈呈　教育支援と人材確保に【岡山】",
      author: "RSK山陽放送",
      published_date: "2023-09-25 16:30:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/740872",
      clean_url: "tbs.co.jp",
      excerpt: "専門学生に土木や建築に関する興味を持ってもらおうと、岡山市の土木工事会社が社債を活用して学校に測量道具を贈りました。岡山科学技術専門学校で贈呈式が行われ、岡山市南区にある土木工事会社・光南の脇本社長… (1ページ)",
      summary: "専門学生に土木や建築に関する興味を持ってもらおうと、岡山市の土木工事会社が社債を活用して学校に測量道具を贈りました。\n\n\n\n岡山科学技術専門学校で贈呈式が行われ、岡山市南区にある土木工事会社・光南の脇本社長から大月校長に測量道具が贈られました。\n\n\n土木や建築に関心のある学生が減るなか少しでも業界に興味をもってもらおうと、光南では銀行とともに社債の発行手数料の一部を教育支援に充てていて、購入した道具は測量の授業などで活用されるということです。\n\n（光南　脇本昌明社長）「日本にはいろんないい技術があると思うので、ちゃんと磨いて将来につなげていっていただけたら」\n\n光南では今後学生を対象にしたインターンシップも実施する予定で、土木工事業の人材確保につなげたいとしています。",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "RSK山陽放送,TBS NEWS DIG",
      media: "https://newsdig.ismcdn.jp/mwimgs/8/d/-/img_8dcc2be4d0dc637568dec8f19c0b4ecd86518.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "c3b2d2deff07339de16d00e28aa2eee5"
    },
    {
      title: "日本テレビ、ジャニーズ事務所の社名変更の検討を要請「口頭で申し入れた」 (2023年9月25日掲載)",
      author: "サンケイスポーツ",
      published_date: "2023-09-25 16:29:12",
      published_date_precision: "timezone unknown",
      link: "https://news.livedoor.com/topics/detail/25050979",
      clean_url: "livedoor.com",
      excerpt: "日本テレビは25日の定例会見で、ジャニーズの性加害に関して発表した。事務所に対して、要望をまとめた申し入れ書を20日に提出したとのこと。担当者が手渡す際に社名変更などの再検討を口頭で申し入れたと説明した",
      summary: "",
      rights: "livedoor.com",
      rank: 3444,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "サンケイスポーツ",
      media: "https://image.news.livedoor.com/newsimage/stf/c/b/cb080_456_137de9fa3699f5f125c8f15ca6d85727.jpg",
      is_opinion: false,
      twitter_account: "@livedoornews",
      _score: null,
      _id: "d8c68aaaeefcd71c7e0e360fc1b987f2"
    },
    {
      title: "メキシコの男女2人がビーチで雷に打たれ死亡 周囲からは「悲鳴」 (2023年9月25日掲載)",
      author: "Techinsight",
      published_date: "2023-09-25 16:28:27",
      published_date_precision: "timezone unknown",
      link: "https://news.livedoor.com/topics/detail/25051008/",
      clean_url: "livedoor.com",
      excerpt: "世界では年間1000人ほどが落雷の被害に遭うと言われているが、このほどメキシコのビーチで雷に打たれて男女2人が死亡する事故が発生した。落雷の瞬間は当時、その場にいた海水浴客と思われる人物が撮影しており、動",
      summary: "世界では年間1000人ほどが落雷の被害に遭うと言われているが、このほどメキシコのビーチで雷に打たれて男女2人が死亡する事故が発生した。落雷の瞬間は当時、その場にいた海水浴客と思われる人物が撮影しており、動画がSNS上で拡散され、衝撃が広がっている。米ニュースメディア『New York Post』などが伝えた。【この記事の他の写真を見る】【この記事の動画を見る】メキシコ中西部に位置するミチョアカン州のマルアタ・ビーチで",
      rights: "livedoor.com",
      rank: 3444,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "Techinsight",
      media: "https://image.news.livedoor.com/newsimage/stf/d/0/d0121_196_4adc7b3d_9389fdd5.jpg",
      is_opinion: false,
      twitter_account: "@livedoornews",
      _score: null,
      _id: "9c3671bc5c5abd0678c2a25b7a1b26f7"
    },
    {
      title: "【速報】特殊詐欺グループ「かけ子」'リーダー格'の男ら逮捕　被害総額は2.8億円か　大阪府警",
      author: "毎日放送",
      published_date: "2023-09-25 16:28:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/741488",
      clean_url: "tbs.co.jp",
      excerpt: "特殊詐欺グループのリーダー格とみられる男らが逮捕されました。被害総額は2億8000万円にのぼるとみられています。詐欺などの疑いで逮捕されたのは、大阪市西区の立花健容疑者（36）ら男女あわせて6人です。警察に… (1ページ)",
      summary: "特殊詐欺グループのリーダー格とみられる男らが逮捕されました。被害総額は2億8000万円にのぼるとみられています。\n詐欺などの疑いで逮捕されたのは、大阪市西区の立花健容疑者（36）ら男女あわせて6人です。\n警察によりますと、立花容疑者らは去年12月から今年6月にかけて、市役所の職員になりすまして「医療費の還付金が受け取れる」とウソを言ってキャッシュカードを盗むなどして、大阪府寝屋川市に住む80代女性ら4人から現金計約500万円をだまし取った疑いが持たれています。\n警察は6人の認否を明らかにしていませんが、SNSの記録などから立花容疑者が特殊詐欺グループの「かけ子」のリーダー格とみて調べています。\nこのグループは数百人から約2億8000万円をだまし取っていたとみられ、警察はグループの実態解明を進める方針です。",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "TBS NEWS DIG,毎日放送",
      media: "https://newsdig.ismcdn.jp/mwimgs/6/f/-/img_6ffa90e6725a30b7f37821ce45e83b1a159667.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "ff2b76948fc082adad5963abe19f95ce"
    },
    {
      title: "物流業界の2024年問題へ対応　新配送拠点稼働スタート",
      author: "北陸放送",
      published_date: "2023-09-25 16:28:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/741606?display=1",
      clean_url: "tbs.co.jp",
      excerpt: "トラックドライバーの時間外労働の制限など、物流業界の2024年問題を見据え、企業も対応に乗り出しています。飲料メーカー・サントリーの新たな配送拠点「石川金沢配送センター」が、8月から石川県白山市で稼働を… (1ページ)",
      summary: "トラックドライバーの時間外労働の制限など、物流業界の2024年問題を見据え、企業も対応に乗り出しています。\n\n石川金沢配送センター\n\n\r\n飲料メーカー・サントリーの新たな配送拠点「石川金沢配送センター」が、8月から石川県白山市で稼働を始めています。\n\n\r\nこれまで9か所あった倉庫を1つにまとめ、最新の自動システムにより、作業の効率化や人手不足の解消を目指します。\n\nサントリーホールディングス 物流部 大泉雪子 部長\n\n\r\nサントリーホールディングス 物流部・大泉雪子 部長\r\n「（商品を）届けてはじめてわれわれのビジネスが成り立つ。人手ではなくて自動でできるものに対しては、今後も取り組んでいきたい」\n\nサントリーでは施設の稼働により、ドライバーの労働時間を年間およそ4400時間削減できるとみています。",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "TBS NEWS DIG,北陸放送",
      media: "https://newsdig.ismcdn.jp/mwimgs/9/0/-/img_90aac786aec4bc416bad19a64f56db96262245.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "d0f761b23b766efe911c5ba844558d84"
    },
    {
      title: "大麻所持の疑いでCHEHONを逮捕 代表曲をめぐり「伏線回収」との指摘 (2023年9月25日掲載)",
      author: "J-CASTニュース",
      published_date: "2023-09-25 16:27:51",
      published_date_precision: "timezone unknown",
      link: "https://news.livedoor.com/topics/detail/25051078",
      clean_url: "livedoor.com",
      excerpt: "レゲエ歌手「CHEHON」が大麻所持容疑で逮捕されたと報じられた。代表曲「みどり」が、SNSなどで「壮大な伏線回収」などと話題に。歌詞の内容などから「みどり」は大麻を指しているのではと解釈されていた",
      summary: "",
      rights: "livedoor.com",
      rank: 3444,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "J-CASTニュース",
      media: "https://image.news.livedoor.com/newsimage/stf/0/1/012f2_80_99d1cfba_f1849ad9.png",
      is_opinion: false,
      twitter_account: "@livedoornews",
      _score: null,
      _id: "3c8ebee95580001c969f94ee5fc4e495"
    },
    {
      title: "「普段いただいている命の大切さを伝えたい」「ごはん大好き！」実りの秋　園児たちが稲刈り体験",
      author: "テレビ高知",
      published_date: "2023-09-25 16:27:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/741540?display=1",
      clean_url: "tbs.co.jp",
      excerpt: "高知市の園児たちが自分たちで植えた稲の収穫体験をしました。「よいしょ、よいしょ」と声を出しながら、一生懸命稲刈りをしました。「よいしょ、よいしょ、よいしょ、うわぁー、でーきた」稲刈り体験をしたのは高… (1ページ)",
      summary: "高知市の園児たちが自分たちで植えた稲の収穫体験をしました。「よいしょ、よいしょ」と声を出しながら、一生懸命稲刈りをしました。\n「よいしょ、よいしょ、よいしょ、うわぁー、でーきた」\n稲刈り体験をしたのは高知市の芸術学園幼稚園の年長組の園児たちです。幼稚園では10年以上前から食育の一環として、地元の農家と一緒に米作りを行っています。収穫したのは今年5月に園児たちが植えた「ヒノヒカリ」です。園児たちは保護者に手伝ってもらいながら、一生懸命、鎌で稲を刈り取っていきました。\n（園児）\r\n「（Ｑどうだった）楽しかった。ちょっと難しかった」\r\n（保護者）\r\n「初めての体験をさせてあげられたのでよかったと思います」\r\n（園児）\r\n「大変だった」\r\n「（Qどんなところが難しかった）稲を切るところ」\r\n「（Qどんな風に食べたい）おいしく」\r\n「（Q何をかけて食べてみたい）明太子」\n収穫したお米は、12月に、給食に出される予定です。\n（担任）\r\n「ふだん、食卓に出ているお米がどうやってできているか、作っている人の大変さを知ってもらえれば。これから食育ということで食べ物の大切さ、普段いただいている命の大切さを",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "TBS NEWS DIG,テレビ高知",
      media: "https://newsdig.ismcdn.jp/mwimgs/f/0/-/img_f03579885a93f16af2ec409c4d7f7b48294410.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "ff82319ef73cd0cf47fe045fbbb576da"
    },
    {
      title: "コキアの紅葉始まる　大分農業文化公園",
      author: "大分放送",
      published_date: "2023-09-25 16:27:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/741482",
      clean_url: "tbs.co.jp",
      excerpt: "大分県杵築市の大分農業文化公園「るるパーク」ではふんわりと丸い形をした植物、コキアの紅葉が始まっています。大分農業文化公園のフラワーガーデンでは広さ5000平方メートルの畑におよそ4000株のコキアが植えら… (1ページ)",
      summary: "大分県杵築市の大分農業文化公園「るるパーク」ではふんわりと丸い形をした植物、コキアの紅葉が始まっています。\n大分農業文化公園のフラワーガーデンでは広さ5000平方メートルの畑におよそ4000株のコキアが植えられています。夏の間の緑色からほんのり赤く色づき始めています。今年は9月に入っても気温が高い日が多かったことから例年に比べゆっくりと紅葉しています。\n\n大分農業文化公園中西省吾さん「涼しくなりましたのでこの寒暖差でかなり赤くなってきますので今から10月になれば十分な見頃を迎えられると思います」\n全体が紅葉するまでの緑と赤のグラデーションも美しく、夏とは一味違った光景が楽しめます。",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "TBS NEWS DIG,大分放送",
      media: "https://newsdig.ismcdn.jp/mwimgs/4/7/-/img_4798a382a986757c9a85f14302ba8402271150.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "5834abc3cf589eaff1da5ea6928a7818"
    },
    {
      title: "露骨にもほどがある！　渡辺直美、'伝説のAIロボ'にウキウキで接近も……「何もしてないのに秒で」「めっちゃ嫌な顔されたw」",
      author: "羽野源一郎",
      published_date: "2023-09-25 16:25:00",
      published_date_precision: "timezone unknown",
      link: "https://nlab.itmedia.co.jp/nl/articles/2309/25/news132.html",
      clean_url: "itmedia.co.jp",
      excerpt: "最後は機嫌を直してくれたとのこと。 (1/2)",
      summary: "最後は機嫌を直してくれたとのこと。",
      rights: "itmedia.co.jp",
      rank: 3371,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "羽野源一郎",
      media: "https://image.itmedia.co.jp/nl/articles/2309/25/cover_news132.jpg",
      is_opinion: false,
      twitter_account: "@itm_nlab",
      _score: null,
      _id: "b5f6125a2b7c27c7d296be34f8688f97"
    },
    {
      title: "長崎ヴェルカ TOP10入り！3連勝で2次ラウンドを突破【バスケットボール天皇杯】",
      author: "長崎放送",
      published_date: "2023-09-25 16:25:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/741538",
      clean_url: "tbs.co.jp",
      excerpt: "バスケットボール天皇杯、B1の長崎ヴェルカは先週金曜日からの2次ラウンド3連戦を突破し、3次ラウンドに駒を進めました。クラブ初の天皇杯トップ10入りを果たしています。負けたら即敗退のトーナメント戦。2次ラウ… (1ページ)",
      summary: "バスケットボール天皇杯、B1の長崎ヴェルカは先週金曜日からの2次ラウンド3連戦を突破し、3次ラウンドに駒を進めました。\r\nクラブ初の天皇杯トップ10入りを果たしています。\n第2戦　長崎ヴェルカ　86-82　大阪エヴェッサ（9/23）\n負けたら即敗退のトーナメント戦。\r\n2次ラウンド初戦で三重を破ったヴェルカの第2戦の相手は、B1の大阪との対戦です。\r\n今シーズン、同じ西地区で戦うライバルに対し、ヴェルカは9点をリードして前半を折り返します。\r\nところが、その後ジリジリと追い上げられ、試合時間残り2分23秒で、大阪に逆転を許します。\r\nそれでもヴェルカは慌てません。すぐに再逆転し4点差で大阪に競り勝ちました。\n第3戦　長崎ヴェルカ　97-64　信州ブレイブウォリアーズ（9/24）\nB1チームとの連戦となった24日の第3戦。\r\nヴェルカの相手は昨シーズンB1中地区3位の信州です。\r\n序盤はクロスゲームに。\r\nヴェルカは前半を1点ビハインドで終えるも、後半に入ると自慢のディフェンスが牙をむきました。\r\n新加入の元NBAプレーヤー ジャレル・ブラントリーが第3クォーターだけで6本のスティールを",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "TBS NEWS DIG,長崎放送",
      media: "https://newsdig.ismcdn.jp/mwimgs/c/2/-/img_c23052348a8497f394b5370a67021875288316.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "673df3ea4a32b953aaf4ad83a5c28bfb"
    },
    {
      title: "大学の統合・再編促進策を中教審に諮問",
      author: "",
      published_date: "2023-09-25 16:25:00",
      published_date_precision: "timezone unknown",
      link: "https://www.shimotsuke.co.jp/articles/-/794652",
      clean_url: "shimotsuke.co.jp",
      excerpt: "盛山正仁文部科学相は２５日、少子化の加速を踏まえた高等教育機関の在り方の検討を中教審に諮問した。大学の統合・再編の促進を議論の柱とし、２０２５年３月までに答申を得たい考え。",
      summary: "盛山正仁文部科学相は２５日、少子化の加速を踏まえた高等教育機関の在り方の検討を中教審に諮問した。大学の統合・再編の促進を議論の柱とし、２０２５年３月までに答申を得たい考え。\n \n \n \nトップニュース",
      rights: "shimotsuke.co.jp",
      rank: 21874,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "",
      media: "http://www.shimotsuke.co.jp/common/soon/images/v1/common/ogp-image.png",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "b623cb36ac9a16c70a12f179120d0b51"
    },
    {
      title: "ロシア勢の「中立」出場を批判",
      author: "",
      published_date: "2023-09-25 16:23:00",
      published_date_precision: "timezone unknown",
      link: "https://www.shimotsuke.co.jp/articles/-/794649",
      clean_url: "shimotsuke.co.jp",
      excerpt: "【ベオグラード共同】東京五輪でウクライナ勢唯一の金メダルを獲得したレスリング男子グレコローマンスタイル８７キロ級のジャン・ベレニュクが２４日、ベオグラードで開催された世界選手権にロシアとベラルーシ勢が個人の中立選手（ＡＩＮ）として出場したことを批判した。…",
      summary: "【ベオグラード共同】東京五輪でウクライナ勢唯一の金メダルを獲得したレスリング男子グレコローマンスタイル８７キロ級のジャン・ベレニュクが２４日、ベオグラードで開催された世界選手権にロシアとベラルーシ勢が個人の中立選手（ＡＩＮ）として出場したことを批判した。\n\n\n　国会議員も務めるベレニュクはロシアの侵攻が続く状況で「政治とスポーツが分離されるべきだというのは分かっているが、ウクライナ市民は毎日、ロシアの爆撃で亡くなっている。彼らの自由や未来を考えたことはあるのか」と訴えた。ロシア、ベラルーシ勢は昨年大会は除外された。ＡＩＮとしながらも、プーチン氏に同調している選手がいると主張した。",
      rights: "shimotsuke.co.jp",
      rank: 21874,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "",
      media: "https://soon.ismcdn.jp/mwimgs/1/1/1200wm/img_11a0f7b53d37006dcd1f701c31ae092019898.jpg",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "55a68cc2386b11c7fbe479b3ca1f667e"
    },
    {
      title: "「横綱になる資格ない」大関・貴景勝の注文相撲にSNSで厳しい批判 (2023年9月25日掲載)",
      author: "Smart FLASH",
      published_date: "2023-09-25 16:21:29",
      published_date_precision: "timezone unknown",
      link: "https://news.livedoor.com/topics/detail/25051655/",
      clean_url: "livedoor.com",
      excerpt: "優勝決定戦で熱海富士（下）をはたき込みで下した貴景勝（写真・時事通信）9月24日に千秋楽を迎えた大相撲秋場所（東京・両国国技館）は、大関・貴景勝の4度めの優勝で幕を閉じた。7月の名古屋場所は、両膝の怪",
      summary: "優勝決定戦で熱海富士（下）をはたき込みで下した貴景勝（写真・時事通信）9月24日に千秋楽を迎えた大相撲秋場所（東京・両国国技館）は、大関・貴景勝の4度めの優勝で幕を閉じた。7月の名古屋場所は、両膝の怪我の影響で全休。カド番で迎えた場所で、前頭・熱海富士との優勝決定戦を制しての逆転優勝だが、SNSでは厳しい批判にさらされている。《まぁ、今回の件で貴景勝関は嫌いになりました。横綱になって欲しくて応援してた",
      rights: "livedoor.com",
      rank: 3444,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "Smart FLASH",
      media: "https://image.news.livedoor.com/newsimage/stf/d/0/d0144_1581_13a1db3735fb7ab6354606c8b974b036.jpg",
      is_opinion: false,
      twitter_account: "@livedoornews",
      _score: null,
      _id: "c4071db874e990302f5181f135466841"
    },
    {
      title: "チェリーランドさがえ 観光振興で戸沢村と連携協定",
      author: "テレビユー山形",
      published_date: "2023-09-25 16:21:00",
      published_date_precision: "timezone unknown",
      link: "https://newsdig.tbs.co.jp/articles/-/741470",
      clean_url: "tbs.co.jp",
      excerpt: "観光事業を盛り上げようとチェリーランドさがえと戸沢村が連携協定を結びました。これはチェリーランドさがえと戸沢村がお互いに魅力を発信し観光振興を図ろうと行われたものです。チェリーランドさがえでは、レス… (1ページ)",
      summary: "観光事業を盛り上げようとチェリーランドさがえと戸沢村が連携協定を結びました。\nこれはチェリーランドさがえと戸沢村がお互いに魅力を発信し観光振興を図ろうと行われたものです。\n\nチェリーランドさがえでは、レストランでブランド豚の戸澤豚一番育ちを使用したメニューをすでに提供しているほか、「とざわMURA市」を来月21日にチェリーランドさがえで開く予定です。\nまた、戸沢村の観光施設でも寒河江市の特産品の販売を行うということです。\n戸沢村・加藤文明村長「観光面、人の流れなどつながりを、ぜひ戸沢村にもつないでくれれば」\nチェリーランドさがえ取締役会長・佐藤洋樹寒河江市長「チェリーランド、戸沢村さん両方が、さらに観光振興で大変有意義な交流になる」",
      rights: "tbs.co.jp",
      rank: 3539,
      topic: "news",
      country: "JP",
      language: "ja",
      authors: "TBS NEWS DIG,テレビユー山形",
      media: "https://newsdig.ismcdn.jp/mwimgs/f/a/-/img_fa876a46bf61f1a9f6802fb36e6c2949157963.jpg",
      is_opinion: false,
      twitter_account: "@tbs_news",
      _score: null,
      _id: "c25c889359395d5e39d399a9b6d8edf3"
    }
  ],
  user_input: {
    lang: [
      "ja"
    ],
    not_lang: null,
    countries: [
      "JP"
    ],
    not_countries: null,
    page: 1,
    size: 50,
    sources: null,
    not_sources: [],
    topic: null,
    from: "2023-09-11 16:47:47"
  }
}